---
- hosts: shubao_go
  gather_facts: False  
  remote_user: '{{common.user_apigateway}}'
  roles:
    - shubao_go
  tags:
    - shubao_go

- hosts: memcached
  remote_user: '{{common.user_console}}'
  gather_facts: False    
  roles:
    - jdk
    - memcached
  tags:
    - memcached
  
- hosts: kafka
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False  
  roles:
    - jdk
    - zookeeper
  tags:
    - zookeeper
  
- hosts: kafka
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False    
  roles:
    - jdk
    - kafka
  tags:
    - kafka
    
- hosts: asgard
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False  
  roles:
    - jdk
    - asgard
  tags:
    - asgard

- hosts: shubao
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False  
  roles:
    - jdk
    - tomcat
    - apigateway
  tags:
    - apigateway 
    
- hosts: shubao_go
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False  
  roles:
    - shubao_go
  tags:
    - apigateway     

- hosts: silvan
  remote_user: '{{common.user_console}}'
  gather_facts: False    
  roles:
    - jdk
    - silvan
  tags:
    - silvan 
    
- hosts: silvan
  remote_user: '{{common.user_console}}'
  gather_facts: False  
  roles:
    - config_gaussdb_backup
  tags:
    - config_db_backup     
    
- hosts: nginx
  remote_user: '{{common.user_console}}'
  gather_facts: False  
  roles:
    - jdk
    - nginx
  tags:
    - nginx  

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  roles:
    - ntp
    - dns
    - common
  tags:
    - common
    
- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - ntp
    - dns
    - common
  tags:
    - common   

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - dns
  tags:
    - dns
    
- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - dns
  tags:
    - dns

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ntp
  tags:
    - ntp
    
- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - ntp
  tags:
    - ntp     

- hosts: initsysuser
  remote_user: '{{common.root_user}}'
  gather_facts: False
  roles:
    - initsysuser
  tags:
    - initsysuser
    
- hosts: common
  gather_facts: False
  roles:
    - update_password
  tags:
    - update_password    

- hosts: initsysuser
  remote_user: '{{common.root_user}}'
  gather_facts: False
  roles:
    - initsystem
  tags:
    - initsystem 

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - jdk
  tags:
    - jdk
    
- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - jdk
  tags:
    - jdk 
    
- hosts: ha_nginx_shubao
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_info
  tags:
    - ha_info_shubao

- hosts: ha_nginx_shubao
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_nginx
  tags:
    - ha_nginx_shubao

- hosts: ha_nginx_silvan
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_info
  tags:
    - ha_info_silvan    

- hosts: ha_nginx_silvan
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_nginx
  tags:
    - ha_nginx_silvan

- hosts: ha_nginx_pod_shubao
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_info
  tags:
    - ha_info_pod_shubao

- hosts: ha_nginx_pod_shubao
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - ha_nginx
  tags:
    - ha_nginx_pod_shubao
 
- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - health_check
  tags:
    - health_check
    
- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - health_check
  tags:
    - health_check  
    
- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - base_check
  tags:
    - base_check
    
- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - base_check
  tags:
    - base_check    
    
- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - cancel_root
  tags:
    - cancel_root    

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - cancel_root
  tags:
    - cancel_root

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - before_deploy
  tags:
    - before_deploy    

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - before_deploy
  tags:
    - before_deploy  

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - base_check
  tags:
    - base_check   

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - base_check
  tags:
    - base_check 

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - health_check
  tags:
    - health_check

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - health_check
  tags:
    - health_check  

- hosts: common_onframework
  remote_user: '{{common.user_console}}'
  gather_facts: False
  roles:
    - before_deploy
  tags:
    - before_deploy

- hosts: common_apigateway
  remote_user: '{{common.user_apigateway}}'
  gather_facts: False
  roles:
    - before_deploy
  tags:
    - before_deploy 

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
    - check_var
  tags:
    - check_var
